# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_jobs" "all" {}

data "netbox_jobs" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "jobs_ids" {
  value = data.netbox_jobs.filtered.items[*].id
}
