# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_power_feed" "example" {
  power_panel_id = netbox_power_panel.example.id
  name = "example"
}
