# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_cooling_feed" "example" {
  cooling_source_id = netbox_cooling_source.example.id
  name = "example"
}
