# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_sites" "all" {}

data "netbox_sites" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "sites_ids" {
  value = data.netbox_sites.filtered.items[*].id
}
