# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_locations" "all" {}

data "netbox_locations" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "locations_ids" {
  value = data.netbox_locations.filtered.items[*].id
}
