# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
# netbox_token can be imported by its NetBox object ID.
terraform import netbox_token.example 123
