# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_contact_assignments" "all" {}

data "netbox_contact_assignments" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "contact_assignments_ids" {
  value = data.netbox_contact_assignments.filtered.items[*].id
}
