# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_power_outlet" "example" {
  device_id = netbox_device.example.id
  name = "example"
}
