# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
# netbox_l2vpn can be imported by its NetBox object ID.
terraform import netbox_l2vpn.example 123
