# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_webhooks" "all" {}

data "netbox_webhooks" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "webhooks_ids" {
  value = data.netbox_webhooks.filtered.items[*].id
}
