# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_device_bays" "all" {}

data "netbox_device_bays" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "device_bays_ids" {
  value = data.netbox_device_bays.filtered.items[*].id
}
