# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_circuit_group_assignment" "example" {
  group_id = netbox_circuit_group.example.id
  member_type = "example"
  member_id = 1
}
