# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_virtual_disk" "example" {
  virtual_machine_id = netbox_virtual_machine.example.id
  name = "example"
  size = 1
}
