# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
# netbox_cluster_group can be imported by its NetBox object ID.
terraform import netbox_cluster_group.example 123
