# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_rack_reservation" "example" {
  rack_id = netbox_rack.example.id
  units = []
  user_id = netbox_user.example.id
  description = "example"
}
