# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_custom_links" "all" {}

data "netbox_custom_links" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "custom_links_ids" {
  value = data.netbox_custom_links.filtered.items[*].id
}
