# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
# netbox_wireless_link can be imported by its NetBox object ID.
terraform import netbox_wireless_link.example 123
