# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_wireless_link" "example" {
  interface_a_id = netbox_interface.example.id
  interface_b_id = netbox_interface.example.id
}
