# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_tunnels" "all" {}

data "netbox_tunnels" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "tunnels_ids" {
  value = data.netbox_tunnels.filtered.items[*].id
}
