# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_service_templates" "all" {}

data "netbox_service_templates" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "service_templates_ids" {
  value = data.netbox_service_templates.filtered.items[*].id
}
