// Code generated by openapi-generator from the NetBox 4.7.0 OpenAPI document. DO NOT EDIT.

/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.0 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the AvailableVLAN type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AvailableVLAN{}

// AvailableVLAN Representation of a VLAN which does not exist in the database.
type AvailableVLAN struct {
	Vid                  *int32                 `json:"vid,omitempty"`
	Group                NullableBriefVLANGroup `json:"group,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AvailableVLAN AvailableVLAN

// NewAvailableVLAN instantiates a new AvailableVLAN object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAvailableVLAN() *AvailableVLAN {
	this := AvailableVLAN{}
	return &this
}

// NewAvailableVLANWithDefaults instantiates a new AvailableVLAN object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAvailableVLANWithDefaults() *AvailableVLAN {
	this := AvailableVLAN{}
	return &this
}

// GetVid returns the Vid field value if set, zero value otherwise.
func (o *AvailableVLAN) GetVid() int32 {
	if o == nil || IsNil(o.Vid) {
		var ret int32
		return ret
	}
	return *o.Vid
}

// GetVidOk returns a tuple with the Vid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AvailableVLAN) GetVidOk() (*int32, bool) {
	if o == nil || IsNil(o.Vid) {
		return nil, false
	}
	return o.Vid, true
}

// HasVid returns a boolean if a field has been set.
func (o *AvailableVLAN) HasVid() bool {
	if o != nil && !IsNil(o.Vid) {
		return true
	}

	return false
}

// SetVid gets a reference to the given int32 and assigns it to the Vid field.
func (o *AvailableVLAN) SetVid(v int32) {
	o.Vid = &v
}

// GetGroup returns the Group field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AvailableVLAN) GetGroup() BriefVLANGroup {
	if o == nil || IsNil(o.Group.Get()) {
		var ret BriefVLANGroup
		return ret
	}
	return *o.Group.Get()
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AvailableVLAN) GetGroupOk() (*BriefVLANGroup, bool) {
	if o == nil {
		return nil, false
	}
	return o.Group.Get(), o.Group.IsSet()
}

// HasGroup returns a boolean if a field has been set.
func (o *AvailableVLAN) HasGroup() bool {
	if o != nil && o.Group.IsSet() {
		return true
	}

	return false
}

// SetGroup gets a reference to the given NullableBriefVLANGroup and assigns it to the Group field.
func (o *AvailableVLAN) SetGroup(v BriefVLANGroup) {
	o.Group.Set(&v)
}

// SetGroupNil sets the value for Group to be an explicit nil
func (o *AvailableVLAN) SetGroupNil() {
	o.Group.Set(nil)
}

// UnsetGroup ensures that no value is present for Group, not even an explicit nil
func (o *AvailableVLAN) UnsetGroup() {
	o.Group.Unset()
}

func (o AvailableVLAN) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AvailableVLAN) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Vid) {
		toSerialize["vid"] = o.Vid
	}
	if o.Group.IsSet() {
		toSerialize["group"] = o.Group.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AvailableVLAN) UnmarshalJSON(data []byte) (err error) {
	varAvailableVLAN := _AvailableVLAN{}

	err = json.Unmarshal(data, &varAvailableVLAN)

	if err != nil {
		return err
	}

	*o = AvailableVLAN(varAvailableVLAN)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "vid")
		delete(additionalProperties, "group")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAvailableVLAN struct {
	value *AvailableVLAN
	isSet bool
}

func (v NullableAvailableVLAN) Get() *AvailableVLAN {
	return v.value
}

func (v *NullableAvailableVLAN) Set(val *AvailableVLAN) {
	v.value = val
	v.isSet = true
}

func (v NullableAvailableVLAN) IsSet() bool {
	return v.isSet
}

func (v *NullableAvailableVLAN) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAvailableVLAN(val *AvailableVLAN) *NullableAvailableVLAN {
	return &NullableAvailableVLAN{value: val, isSet: true}
}

func (v NullableAvailableVLAN) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAvailableVLAN) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
