// Code generated by openapi-generator from the NetBox 4.7.0 OpenAPI document. DO NOT EDIT.

/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.0 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the ChoiceInteger type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChoiceInteger{}

// ChoiceInteger A NetBox integer choice field as returned on read: machine value plus human label.
type ChoiceInteger struct {
	Value                NullableInt32  `json:"value,omitempty"`
	Label                NullableString `json:"label,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ChoiceInteger ChoiceInteger

// NewChoiceInteger instantiates a new ChoiceInteger object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChoiceInteger() *ChoiceInteger {
	this := ChoiceInteger{}
	return &this
}

// NewChoiceIntegerWithDefaults instantiates a new ChoiceInteger object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChoiceIntegerWithDefaults() *ChoiceInteger {
	this := ChoiceInteger{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChoiceInteger) GetValue() int32 {
	if o == nil || IsNil(o.Value.Get()) {
		var ret int32
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChoiceInteger) GetValueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *ChoiceInteger) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableInt32 and assigns it to the Value field.
func (o *ChoiceInteger) SetValue(v int32) {
	o.Value.Set(&v)
}

// SetValueNil sets the value for Value to be an explicit nil
func (o *ChoiceInteger) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *ChoiceInteger) UnsetValue() {
	o.Value.Unset()
}

// GetLabel returns the Label field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChoiceInteger) GetLabel() string {
	if o == nil || IsNil(o.Label.Get()) {
		var ret string
		return ret
	}
	return *o.Label.Get()
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChoiceInteger) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Label.Get(), o.Label.IsSet()
}

// HasLabel returns a boolean if a field has been set.
func (o *ChoiceInteger) HasLabel() bool {
	if o != nil && o.Label.IsSet() {
		return true
	}

	return false
}

// SetLabel gets a reference to the given NullableString and assigns it to the Label field.
func (o *ChoiceInteger) SetLabel(v string) {
	o.Label.Set(&v)
}

// SetLabelNil sets the value for Label to be an explicit nil
func (o *ChoiceInteger) SetLabelNil() {
	o.Label.Set(nil)
}

// UnsetLabel ensures that no value is present for Label, not even an explicit nil
func (o *ChoiceInteger) UnsetLabel() {
	o.Label.Unset()
}

func (o ChoiceInteger) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChoiceInteger) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	if o.Label.IsSet() {
		toSerialize["label"] = o.Label.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ChoiceInteger) UnmarshalJSON(data []byte) (err error) {
	varChoiceInteger := _ChoiceInteger{}

	err = json.Unmarshal(data, &varChoiceInteger)

	if err != nil {
		return err
	}

	*o = ChoiceInteger(varChoiceInteger)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		delete(additionalProperties, "label")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChoiceInteger struct {
	value *ChoiceInteger
	isSet bool
}

func (v NullableChoiceInteger) Get() *ChoiceInteger {
	return v.value
}

func (v *NullableChoiceInteger) Set(val *ChoiceInteger) {
	v.value = val
	v.isSet = true
}

func (v NullableChoiceInteger) IsSet() bool {
	return v.isSet
}

func (v *NullableChoiceInteger) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChoiceInteger(val *ChoiceInteger) *NullableChoiceInteger {
	return &NullableChoiceInteger{value: val, isSet: true}
}

func (v NullableChoiceInteger) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChoiceInteger) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
