// Code generated by openapi-generator from the NetBox 4.7.0 OpenAPI document. DO NOT EDIT.

/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.0 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the BriefWirelessLANGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BriefWirelessLANGroup{}

// BriefWirelessLANGroup Base serializer class for models inheriting from NestedGroupModel.
type BriefWirelessLANGroup struct {
	Id                   int32   `json:"id"`
	Url                  *string `json:"url,omitempty"`
	Display              *string `json:"display,omitempty"`
	Name                 *string `json:"name,omitempty"`
	Slug                 *string `json:"slug,omitempty" validate:"regexp=^[-a-zA-Z0-9_]+$"`
	Description          *string `json:"description,omitempty"`
	WirelesslanCount     *int32  `json:"wirelesslan_count,omitempty"`
	Depth                *int32  `json:"_depth,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BriefWirelessLANGroup BriefWirelessLANGroup

// NewBriefWirelessLANGroup instantiates a new BriefWirelessLANGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBriefWirelessLANGroup(id int32) *BriefWirelessLANGroup {
	this := BriefWirelessLANGroup{}
	this.Id = id
	return &this
}

// NewBriefWirelessLANGroupWithDefaults instantiates a new BriefWirelessLANGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBriefWirelessLANGroupWithDefaults() *BriefWirelessLANGroup {
	this := BriefWirelessLANGroup{}
	return &this
}

// GetId returns the Id field value
func (o *BriefWirelessLANGroup) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BriefWirelessLANGroup) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BriefWirelessLANGroup) SetId(v int32) {
	o.Id = v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *BriefWirelessLANGroup) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefWirelessLANGroup) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *BriefWirelessLANGroup) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *BriefWirelessLANGroup) SetUrl(v string) {
	o.Url = &v
}

// GetDisplay returns the Display field value if set, zero value otherwise.
func (o *BriefWirelessLANGroup) GetDisplay() string {
	if o == nil || IsNil(o.Display) {
		var ret string
		return ret
	}
	return *o.Display
}

// GetDisplayOk returns a tuple with the Display field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefWirelessLANGroup) GetDisplayOk() (*string, bool) {
	if o == nil || IsNil(o.Display) {
		return nil, false
	}
	return o.Display, true
}

// HasDisplay returns a boolean if a field has been set.
func (o *BriefWirelessLANGroup) HasDisplay() bool {
	if o != nil && !IsNil(o.Display) {
		return true
	}

	return false
}

// SetDisplay gets a reference to the given string and assigns it to the Display field.
func (o *BriefWirelessLANGroup) SetDisplay(v string) {
	o.Display = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *BriefWirelessLANGroup) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefWirelessLANGroup) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *BriefWirelessLANGroup) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *BriefWirelessLANGroup) SetName(v string) {
	o.Name = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *BriefWirelessLANGroup) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefWirelessLANGroup) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *BriefWirelessLANGroup) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *BriefWirelessLANGroup) SetSlug(v string) {
	o.Slug = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *BriefWirelessLANGroup) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefWirelessLANGroup) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *BriefWirelessLANGroup) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *BriefWirelessLANGroup) SetDescription(v string) {
	o.Description = &v
}

// GetWirelesslanCount returns the WirelesslanCount field value if set, zero value otherwise.
func (o *BriefWirelessLANGroup) GetWirelesslanCount() int32 {
	if o == nil || IsNil(o.WirelesslanCount) {
		var ret int32
		return ret
	}
	return *o.WirelesslanCount
}

// GetWirelesslanCountOk returns a tuple with the WirelesslanCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefWirelessLANGroup) GetWirelesslanCountOk() (*int32, bool) {
	if o == nil || IsNil(o.WirelesslanCount) {
		return nil, false
	}
	return o.WirelesslanCount, true
}

// HasWirelesslanCount returns a boolean if a field has been set.
func (o *BriefWirelessLANGroup) HasWirelesslanCount() bool {
	if o != nil && !IsNil(o.WirelesslanCount) {
		return true
	}

	return false
}

// SetWirelesslanCount gets a reference to the given int32 and assigns it to the WirelesslanCount field.
func (o *BriefWirelessLANGroup) SetWirelesslanCount(v int32) {
	o.WirelesslanCount = &v
}

// GetDepth returns the Depth field value if set, zero value otherwise.
func (o *BriefWirelessLANGroup) GetDepth() int32 {
	if o == nil || IsNil(o.Depth) {
		var ret int32
		return ret
	}
	return *o.Depth
}

// GetDepthOk returns a tuple with the Depth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefWirelessLANGroup) GetDepthOk() (*int32, bool) {
	if o == nil || IsNil(o.Depth) {
		return nil, false
	}
	return o.Depth, true
}

// HasDepth returns a boolean if a field has been set.
func (o *BriefWirelessLANGroup) HasDepth() bool {
	if o != nil && !IsNil(o.Depth) {
		return true
	}

	return false
}

// SetDepth gets a reference to the given int32 and assigns it to the Depth field.
func (o *BriefWirelessLANGroup) SetDepth(v int32) {
	o.Depth = &v
}

func (o BriefWirelessLANGroup) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BriefWirelessLANGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Display) {
		toSerialize["display"] = o.Display
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.WirelesslanCount) {
		toSerialize["wirelesslan_count"] = o.WirelesslanCount
	}
	if !IsNil(o.Depth) {
		toSerialize["_depth"] = o.Depth
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BriefWirelessLANGroup) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varBriefWirelessLANGroup := _BriefWirelessLANGroup{}

	err = json.Unmarshal(data, &varBriefWirelessLANGroup)

	if err != nil {
		return err
	}

	*o = BriefWirelessLANGroup(varBriefWirelessLANGroup)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "url")
		delete(additionalProperties, "display")
		delete(additionalProperties, "name")
		delete(additionalProperties, "slug")
		delete(additionalProperties, "description")
		delete(additionalProperties, "wirelesslan_count")
		delete(additionalProperties, "_depth")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBriefWirelessLANGroup struct {
	value *BriefWirelessLANGroup
	isSet bool
}

func (v NullableBriefWirelessLANGroup) Get() *BriefWirelessLANGroup {
	return v.value
}

func (v *NullableBriefWirelessLANGroup) Set(val *BriefWirelessLANGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableBriefWirelessLANGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableBriefWirelessLANGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBriefWirelessLANGroup(val *BriefWirelessLANGroup) *NullableBriefWirelessLANGroup {
	return &NullableBriefWirelessLANGroup{value: val, isSet: true}
}

func (v NullableBriefWirelessLANGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBriefWirelessLANGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
