// Code generated by openapi-generator from the NetBox 4.7.0 OpenAPI document. DO NOT EDIT.

/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.0 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the AvailableIP type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AvailableIP{}

// AvailableIP Representation of an IP address which does not exist in the database.
type AvailableIP struct {
	Family               *int32           `json:"family,omitempty"`
	Address              *string          `json:"address,omitempty"`
	Vrf                  NullableBriefVRF `json:"vrf,omitempty"`
	Description          *string          `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AvailableIP AvailableIP

// NewAvailableIP instantiates a new AvailableIP object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAvailableIP() *AvailableIP {
	this := AvailableIP{}
	return &this
}

// NewAvailableIPWithDefaults instantiates a new AvailableIP object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAvailableIPWithDefaults() *AvailableIP {
	this := AvailableIP{}
	return &this
}

// GetFamily returns the Family field value if set, zero value otherwise.
func (o *AvailableIP) GetFamily() int32 {
	if o == nil || IsNil(o.Family) {
		var ret int32
		return ret
	}
	return *o.Family
}

// GetFamilyOk returns a tuple with the Family field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AvailableIP) GetFamilyOk() (*int32, bool) {
	if o == nil || IsNil(o.Family) {
		return nil, false
	}
	return o.Family, true
}

// HasFamily returns a boolean if a field has been set.
func (o *AvailableIP) HasFamily() bool {
	if o != nil && !IsNil(o.Family) {
		return true
	}

	return false
}

// SetFamily gets a reference to the given int32 and assigns it to the Family field.
func (o *AvailableIP) SetFamily(v int32) {
	o.Family = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *AvailableIP) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AvailableIP) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *AvailableIP) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *AvailableIP) SetAddress(v string) {
	o.Address = &v
}

// GetVrf returns the Vrf field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AvailableIP) GetVrf() BriefVRF {
	if o == nil || IsNil(o.Vrf.Get()) {
		var ret BriefVRF
		return ret
	}
	return *o.Vrf.Get()
}

// GetVrfOk returns a tuple with the Vrf field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AvailableIP) GetVrfOk() (*BriefVRF, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vrf.Get(), o.Vrf.IsSet()
}

// HasVrf returns a boolean if a field has been set.
func (o *AvailableIP) HasVrf() bool {
	if o != nil && o.Vrf.IsSet() {
		return true
	}

	return false
}

// SetVrf gets a reference to the given NullableBriefVRF and assigns it to the Vrf field.
func (o *AvailableIP) SetVrf(v BriefVRF) {
	o.Vrf.Set(&v)
}

// SetVrfNil sets the value for Vrf to be an explicit nil
func (o *AvailableIP) SetVrfNil() {
	o.Vrf.Set(nil)
}

// UnsetVrf ensures that no value is present for Vrf, not even an explicit nil
func (o *AvailableIP) UnsetVrf() {
	o.Vrf.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AvailableIP) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AvailableIP) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AvailableIP) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AvailableIP) SetDescription(v string) {
	o.Description = &v
}

func (o AvailableIP) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AvailableIP) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Family) {
		toSerialize["family"] = o.Family
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if o.Vrf.IsSet() {
		toSerialize["vrf"] = o.Vrf.Get()
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AvailableIP) UnmarshalJSON(data []byte) (err error) {
	varAvailableIP := _AvailableIP{}

	err = json.Unmarshal(data, &varAvailableIP)

	if err != nil {
		return err
	}

	*o = AvailableIP(varAvailableIP)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "family")
		delete(additionalProperties, "address")
		delete(additionalProperties, "vrf")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAvailableIP struct {
	value *AvailableIP
	isSet bool
}

func (v NullableAvailableIP) Get() *AvailableIP {
	return v.value
}

func (v *NullableAvailableIP) Set(val *AvailableIP) {
	v.value = val
	v.isSet = true
}

func (v NullableAvailableIP) IsSet() bool {
	return v.isSet
}

func (v *NullableAvailableIP) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAvailableIP(val *AvailableIP) *NullableAvailableIP {
	return &NullableAvailableIP{value: val, isSet: true}
}

func (v NullableAvailableIP) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAvailableIP) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
