// Code generated by openapi-generator from the NetBox 4.7.0 OpenAPI document. DO NOT EDIT.

/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.0 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"time"
)

// checks if the BriefJob type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BriefJob{}

// BriefJob struct for BriefJob
type BriefJob struct {
	Url                  *string       `json:"url,omitempty"`
	Status               *ChoiceString `json:"status,omitempty"`
	Created              *time.Time    `json:"created,omitempty"`
	Completed            NullableTime  `json:"completed,omitempty"`
	User                 *BriefUser    `json:"user,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BriefJob BriefJob

// NewBriefJob instantiates a new BriefJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBriefJob() *BriefJob {
	this := BriefJob{}
	return &this
}

// NewBriefJobWithDefaults instantiates a new BriefJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBriefJobWithDefaults() *BriefJob {
	this := BriefJob{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *BriefJob) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefJob) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *BriefJob) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *BriefJob) SetUrl(v string) {
	o.Url = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BriefJob) GetStatus() ChoiceString {
	if o == nil || IsNil(o.Status) {
		var ret ChoiceString
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefJob) GetStatusOk() (*ChoiceString, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BriefJob) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ChoiceString and assigns it to the Status field.
func (o *BriefJob) SetStatus(v ChoiceString) {
	o.Status = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *BriefJob) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefJob) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *BriefJob) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *BriefJob) SetCreated(v time.Time) {
	o.Created = &v
}

// GetCompleted returns the Completed field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BriefJob) GetCompleted() time.Time {
	if o == nil || IsNil(o.Completed.Get()) {
		var ret time.Time
		return ret
	}
	return *o.Completed.Get()
}

// GetCompletedOk returns a tuple with the Completed field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BriefJob) GetCompletedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Completed.Get(), o.Completed.IsSet()
}

// HasCompleted returns a boolean if a field has been set.
func (o *BriefJob) HasCompleted() bool {
	if o != nil && o.Completed.IsSet() {
		return true
	}

	return false
}

// SetCompleted gets a reference to the given NullableTime and assigns it to the Completed field.
func (o *BriefJob) SetCompleted(v time.Time) {
	o.Completed.Set(&v)
}

// SetCompletedNil sets the value for Completed to be an explicit nil
func (o *BriefJob) SetCompletedNil() {
	o.Completed.Set(nil)
}

// UnsetCompleted ensures that no value is present for Completed, not even an explicit nil
func (o *BriefJob) UnsetCompleted() {
	o.Completed.Unset()
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *BriefJob) GetUser() BriefUser {
	if o == nil || IsNil(o.User) {
		var ret BriefUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefJob) GetUserOk() (*BriefUser, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *BriefJob) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given BriefUser and assigns it to the User field.
func (o *BriefJob) SetUser(v BriefUser) {
	o.User = &v
}

func (o BriefJob) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BriefJob) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if o.Completed.IsSet() {
		toSerialize["completed"] = o.Completed.Get()
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BriefJob) UnmarshalJSON(data []byte) (err error) {
	varBriefJob := _BriefJob{}

	err = json.Unmarshal(data, &varBriefJob)

	if err != nil {
		return err
	}

	*o = BriefJob(varBriefJob)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "url")
		delete(additionalProperties, "status")
		delete(additionalProperties, "created")
		delete(additionalProperties, "completed")
		delete(additionalProperties, "user")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBriefJob struct {
	value *BriefJob
	isSet bool
}

func (v NullableBriefJob) Get() *BriefJob {
	return v.value
}

func (v *NullableBriefJob) Set(val *BriefJob) {
	v.value = val
	v.isSet = true
}

func (v NullableBriefJob) IsSet() bool {
	return v.isSet
}

func (v *NullableBriefJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBriefJob(val *BriefJob) *NullableBriefJob {
	return &NullableBriefJob{value: val, isSet: true}
}

func (v NullableBriefJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBriefJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
