// Code generated by openapi-generator from the NetBox 4.7.0 OpenAPI document. DO NOT EDIT.

/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.0 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the CableRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CableRequest{}

// CableRequest Base serializer class for models inheriting from PrimaryModel.
type CableRequest struct {
	// * `cat3` - CAT3 * `cat5` - CAT5 * `cat5e` - CAT5e * `cat6` - CAT6 * `cat6a` - CAT6a * `cat7` - CAT7 * `cat7a` - CAT7a * `cat8` - CAT8 * `mrj21-trunk` - MRJ21 Trunk * `dac-active` - Direct Attach Copper (Active) * `dac-passive` - Direct Attach Copper (Passive) * `coaxial` - Coaxial * `rg-6` - RG-6 * `rg-8` - RG-8 * `rg-11` - RG-11 * `rg-59` - RG-59 * `rg-62` - RG-62 * `rg-213` - RG-213 * `lmr-100` - LMR-100 * `lmr-200` - LMR-200 * `lmr-400` - LMR-400 * `mmf` - Multimode Fiber * `mmf-om1` - Multimode Fiber (OM1) * `mmf-om2` - Multimode Fiber (OM2) * `mmf-om3` - Multimode Fiber (OM3) * `mmf-om4` - Multimode Fiber (OM4) * `mmf-om5` - Multimode Fiber (OM5) * `smf` - Single-mode Fiber * `smf-os1` - Single-mode Fiber (OS1) * `smf-os2` - Single-mode Fiber (OS2) * `aoc` - Active Optical Cabling (AOC) * `power` - Power * `usb` - USB
	Type          NullableString         `json:"type,omitempty"`
	ATerminations []GenericObjectRequest `json:"a_terminations,omitempty"`
	BTerminations []GenericObjectRequest `json:"b_terminations,omitempty"`
	// * `connected` - Connected * `planned` - Planned * `decommissioning` - Decommissioning
	Status *string `json:"status,omitempty"`
	// * `single-1c1p` - 1C1P * `single-1c2p` - 1C2P * `single-1c4p` - 1C4P * `single-1c6p` - 1C6P * `single-1c8p` - 1C8P * `single-1c12p` - 1C12P * `single-1c16p` - 1C16P * `trunk-2c1p` - 2C1P trunk * `trunk-2c2p` - 2C2P trunk * `trunk-2c4p` - 2C4P trunk * `trunk-2c4p-shuffle` - 2C4P trunk (shuffle) * `trunk-2c6p` - 2C6P trunk * `trunk-2c8p` - 2C8P trunk * `trunk-2c12p` - 2C12P trunk * `trunk-4c1p` - 4C1P trunk * `trunk-4c2p` - 4C2P trunk * `trunk-4c4p` - 4C4P trunk * `trunk-4c4p-shuffle` - 4C4P trunk (shuffle) * `trunk-4c6p` - 4C6P trunk * `trunk-4c8p` - 4C8P trunk * `trunk-8c4p` - 8C4P trunk * `breakout-1c2p-2c1p` - 1C2P:2C1P breakout * `breakout-1c4p-4c1p` - 1C4P:4C1P breakout * `breakout-1c6p-6c1p` - 1C6P:6C1P breakout * `breakout-1c8p-8c1p` - 1C8P:8C1P breakout * `breakout-2c4p-8c1p-shuffle` - 2C4P:8C1P breakout (shuffle)
	Profile *string         `json:"profile,omitempty"`
	Tenant  NullableInt32   `json:"tenant,omitempty"`
	Bundle  NullableInt32   `json:"bundle,omitempty"`
	Label   *string         `json:"label,omitempty"`
	Color   *string         `json:"color,omitempty" validate:"regexp=^[0-9a-f]{6}$"`
	Length  NullableFloat64 `json:"length,omitempty"`
	// * `km` - Kilometers * `m` - Meters * `cm` - Centimeters * `mi` - Miles * `ft` - Feet * `in` - Inches
	LengthUnit           NullableString         `json:"length_unit,omitempty"`
	Description          *string                `json:"description,omitempty"`
	Owner                NullableInt32          `json:"owner,omitempty"`
	Comments             *string                `json:"comments,omitempty"`
	Tags                 []NestedTagRequest     `json:"tags,omitempty"`
	CustomFields         map[string]interface{} `json:"custom_fields,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CableRequest CableRequest

// NewCableRequest instantiates a new CableRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCableRequest() *CableRequest {
	this := CableRequest{}
	return &this
}

// NewCableRequestWithDefaults instantiates a new CableRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCableRequestWithDefaults() *CableRequest {
	this := CableRequest{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CableRequest) GetType() string {
	if o == nil || IsNil(o.Type.Get()) {
		var ret string
		return ret
	}
	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CableRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// HasType returns a boolean if a field has been set.
func (o *CableRequest) HasType() bool {
	if o != nil && o.Type.IsSet() {
		return true
	}

	return false
}

// SetType gets a reference to the given NullableString and assigns it to the Type field.
func (o *CableRequest) SetType(v string) {
	o.Type.Set(&v)
}

// SetTypeNil sets the value for Type to be an explicit nil
func (o *CableRequest) SetTypeNil() {
	o.Type.Set(nil)
}

// UnsetType ensures that no value is present for Type, not even an explicit nil
func (o *CableRequest) UnsetType() {
	o.Type.Unset()
}

// GetATerminations returns the ATerminations field value if set, zero value otherwise.
func (o *CableRequest) GetATerminations() []GenericObjectRequest {
	if o == nil || IsNil(o.ATerminations) {
		var ret []GenericObjectRequest
		return ret
	}
	return o.ATerminations
}

// GetATerminationsOk returns a tuple with the ATerminations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CableRequest) GetATerminationsOk() ([]GenericObjectRequest, bool) {
	if o == nil || IsNil(o.ATerminations) {
		return nil, false
	}
	return o.ATerminations, true
}

// HasATerminations returns a boolean if a field has been set.
func (o *CableRequest) HasATerminations() bool {
	if o != nil && !IsNil(o.ATerminations) {
		return true
	}

	return false
}

// SetATerminations gets a reference to the given []GenericObjectRequest and assigns it to the ATerminations field.
func (o *CableRequest) SetATerminations(v []GenericObjectRequest) {
	o.ATerminations = v
}

// GetBTerminations returns the BTerminations field value if set, zero value otherwise.
func (o *CableRequest) GetBTerminations() []GenericObjectRequest {
	if o == nil || IsNil(o.BTerminations) {
		var ret []GenericObjectRequest
		return ret
	}
	return o.BTerminations
}

// GetBTerminationsOk returns a tuple with the BTerminations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CableRequest) GetBTerminationsOk() ([]GenericObjectRequest, bool) {
	if o == nil || IsNil(o.BTerminations) {
		return nil, false
	}
	return o.BTerminations, true
}

// HasBTerminations returns a boolean if a field has been set.
func (o *CableRequest) HasBTerminations() bool {
	if o != nil && !IsNil(o.BTerminations) {
		return true
	}

	return false
}

// SetBTerminations gets a reference to the given []GenericObjectRequest and assigns it to the BTerminations field.
func (o *CableRequest) SetBTerminations(v []GenericObjectRequest) {
	o.BTerminations = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CableRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CableRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CableRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CableRequest) SetStatus(v string) {
	o.Status = &v
}

// GetProfile returns the Profile field value if set, zero value otherwise.
func (o *CableRequest) GetProfile() string {
	if o == nil || IsNil(o.Profile) {
		var ret string
		return ret
	}
	return *o.Profile
}

// GetProfileOk returns a tuple with the Profile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CableRequest) GetProfileOk() (*string, bool) {
	if o == nil || IsNil(o.Profile) {
		return nil, false
	}
	return o.Profile, true
}

// HasProfile returns a boolean if a field has been set.
func (o *CableRequest) HasProfile() bool {
	if o != nil && !IsNil(o.Profile) {
		return true
	}

	return false
}

// SetProfile gets a reference to the given string and assigns it to the Profile field.
func (o *CableRequest) SetProfile(v string) {
	o.Profile = &v
}

// GetTenant returns the Tenant field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CableRequest) GetTenant() int32 {
	if o == nil || IsNil(o.Tenant.Get()) {
		var ret int32
		return ret
	}
	return *o.Tenant.Get()
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CableRequest) GetTenantOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tenant.Get(), o.Tenant.IsSet()
}

// HasTenant returns a boolean if a field has been set.
func (o *CableRequest) HasTenant() bool {
	if o != nil && o.Tenant.IsSet() {
		return true
	}

	return false
}

// SetTenant gets a reference to the given NullableInt32 and assigns it to the Tenant field.
func (o *CableRequest) SetTenant(v int32) {
	o.Tenant.Set(&v)
}

// SetTenantNil sets the value for Tenant to be an explicit nil
func (o *CableRequest) SetTenantNil() {
	o.Tenant.Set(nil)
}

// UnsetTenant ensures that no value is present for Tenant, not even an explicit nil
func (o *CableRequest) UnsetTenant() {
	o.Tenant.Unset()
}

// GetBundle returns the Bundle field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CableRequest) GetBundle() int32 {
	if o == nil || IsNil(o.Bundle.Get()) {
		var ret int32
		return ret
	}
	return *o.Bundle.Get()
}

// GetBundleOk returns a tuple with the Bundle field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CableRequest) GetBundleOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Bundle.Get(), o.Bundle.IsSet()
}

// HasBundle returns a boolean if a field has been set.
func (o *CableRequest) HasBundle() bool {
	if o != nil && o.Bundle.IsSet() {
		return true
	}

	return false
}

// SetBundle gets a reference to the given NullableInt32 and assigns it to the Bundle field.
func (o *CableRequest) SetBundle(v int32) {
	o.Bundle.Set(&v)
}

// SetBundleNil sets the value for Bundle to be an explicit nil
func (o *CableRequest) SetBundleNil() {
	o.Bundle.Set(nil)
}

// UnsetBundle ensures that no value is present for Bundle, not even an explicit nil
func (o *CableRequest) UnsetBundle() {
	o.Bundle.Unset()
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *CableRequest) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CableRequest) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *CableRequest) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *CableRequest) SetLabel(v string) {
	o.Label = &v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *CableRequest) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CableRequest) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *CableRequest) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *CableRequest) SetColor(v string) {
	o.Color = &v
}

// GetLength returns the Length field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CableRequest) GetLength() float64 {
	if o == nil || IsNil(o.Length.Get()) {
		var ret float64
		return ret
	}
	return *o.Length.Get()
}

// GetLengthOk returns a tuple with the Length field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CableRequest) GetLengthOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Length.Get(), o.Length.IsSet()
}

// HasLength returns a boolean if a field has been set.
func (o *CableRequest) HasLength() bool {
	if o != nil && o.Length.IsSet() {
		return true
	}

	return false
}

// SetLength gets a reference to the given NullableFloat64 and assigns it to the Length field.
func (o *CableRequest) SetLength(v float64) {
	o.Length.Set(&v)
}

// SetLengthNil sets the value for Length to be an explicit nil
func (o *CableRequest) SetLengthNil() {
	o.Length.Set(nil)
}

// UnsetLength ensures that no value is present for Length, not even an explicit nil
func (o *CableRequest) UnsetLength() {
	o.Length.Unset()
}

// GetLengthUnit returns the LengthUnit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CableRequest) GetLengthUnit() string {
	if o == nil || IsNil(o.LengthUnit.Get()) {
		var ret string
		return ret
	}
	return *o.LengthUnit.Get()
}

// GetLengthUnitOk returns a tuple with the LengthUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CableRequest) GetLengthUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LengthUnit.Get(), o.LengthUnit.IsSet()
}

// HasLengthUnit returns a boolean if a field has been set.
func (o *CableRequest) HasLengthUnit() bool {
	if o != nil && o.LengthUnit.IsSet() {
		return true
	}

	return false
}

// SetLengthUnit gets a reference to the given NullableString and assigns it to the LengthUnit field.
func (o *CableRequest) SetLengthUnit(v string) {
	o.LengthUnit.Set(&v)
}

// SetLengthUnitNil sets the value for LengthUnit to be an explicit nil
func (o *CableRequest) SetLengthUnitNil() {
	o.LengthUnit.Set(nil)
}

// UnsetLengthUnit ensures that no value is present for LengthUnit, not even an explicit nil
func (o *CableRequest) UnsetLengthUnit() {
	o.LengthUnit.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CableRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CableRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CableRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CableRequest) SetDescription(v string) {
	o.Description = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CableRequest) GetOwner() int32 {
	if o == nil || IsNil(o.Owner.Get()) {
		var ret int32
		return ret
	}
	return *o.Owner.Get()
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CableRequest) GetOwnerOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Owner.Get(), o.Owner.IsSet()
}

// HasOwner returns a boolean if a field has been set.
func (o *CableRequest) HasOwner() bool {
	if o != nil && o.Owner.IsSet() {
		return true
	}

	return false
}

// SetOwner gets a reference to the given NullableInt32 and assigns it to the Owner field.
func (o *CableRequest) SetOwner(v int32) {
	o.Owner.Set(&v)
}

// SetOwnerNil sets the value for Owner to be an explicit nil
func (o *CableRequest) SetOwnerNil() {
	o.Owner.Set(nil)
}

// UnsetOwner ensures that no value is present for Owner, not even an explicit nil
func (o *CableRequest) UnsetOwner() {
	o.Owner.Unset()
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *CableRequest) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CableRequest) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *CableRequest) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *CableRequest) SetComments(v string) {
	o.Comments = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *CableRequest) GetTags() []NestedTagRequest {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTagRequest
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CableRequest) GetTagsOk() ([]NestedTagRequest, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CableRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTagRequest and assigns it to the Tags field.
func (o *CableRequest) SetTags(v []NestedTagRequest) {
	o.Tags = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *CableRequest) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CableRequest) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *CableRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *CableRequest) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

func (o CableRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CableRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type.IsSet() {
		toSerialize["type"] = o.Type.Get()
	}
	if !IsNil(o.ATerminations) {
		toSerialize["a_terminations"] = o.ATerminations
	}
	if !IsNil(o.BTerminations) {
		toSerialize["b_terminations"] = o.BTerminations
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Profile) {
		toSerialize["profile"] = o.Profile
	}
	if o.Tenant.IsSet() {
		toSerialize["tenant"] = o.Tenant.Get()
	}
	if o.Bundle.IsSet() {
		toSerialize["bundle"] = o.Bundle.Get()
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if o.Length.IsSet() {
		toSerialize["length"] = o.Length.Get()
	}
	if o.LengthUnit.IsSet() {
		toSerialize["length_unit"] = o.LengthUnit.Get()
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if o.Owner.IsSet() {
		toSerialize["owner"] = o.Owner.Get()
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CableRequest) UnmarshalJSON(data []byte) (err error) {
	varCableRequest := _CableRequest{}

	err = json.Unmarshal(data, &varCableRequest)

	if err != nil {
		return err
	}

	*o = CableRequest(varCableRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "a_terminations")
		delete(additionalProperties, "b_terminations")
		delete(additionalProperties, "status")
		delete(additionalProperties, "profile")
		delete(additionalProperties, "tenant")
		delete(additionalProperties, "bundle")
		delete(additionalProperties, "label")
		delete(additionalProperties, "color")
		delete(additionalProperties, "length")
		delete(additionalProperties, "length_unit")
		delete(additionalProperties, "description")
		delete(additionalProperties, "owner")
		delete(additionalProperties, "comments")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "custom_fields")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCableRequest struct {
	value *CableRequest
	isSet bool
}

func (v NullableCableRequest) Get() *CableRequest {
	return v.value
}

func (v *NullableCableRequest) Set(val *CableRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCableRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCableRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCableRequest(val *CableRequest) *NullableCableRequest {
	return &NullableCableRequest{value: val, isSet: true}
}

func (v NullableCableRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCableRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
