// Code generated by openapi-generator from the NetBox 4.7.0 OpenAPI document. DO NOT EDIT.

/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.0 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the FrontPortMapping type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FrontPortMapping{}

// FrontPortMapping struct for FrontPortMapping
type FrontPortMapping struct {
	Position             *int32 `json:"position,omitempty"`
	RearPort             *int32 `json:"rear_port,omitempty"`
	RearPortPosition     *int32 `json:"rear_port_position,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FrontPortMapping FrontPortMapping

// NewFrontPortMapping instantiates a new FrontPortMapping object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFrontPortMapping() *FrontPortMapping {
	this := FrontPortMapping{}
	var rearPortPosition int32 = 1
	this.RearPortPosition = &rearPortPosition
	return &this
}

// NewFrontPortMappingWithDefaults instantiates a new FrontPortMapping object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFrontPortMappingWithDefaults() *FrontPortMapping {
	this := FrontPortMapping{}
	var rearPortPosition int32 = 1
	this.RearPortPosition = &rearPortPosition
	return &this
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *FrontPortMapping) GetPosition() int32 {
	if o == nil || IsNil(o.Position) {
		var ret int32
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FrontPortMapping) GetPositionOk() (*int32, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *FrontPortMapping) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int32 and assigns it to the Position field.
func (o *FrontPortMapping) SetPosition(v int32) {
	o.Position = &v
}

// GetRearPort returns the RearPort field value if set, zero value otherwise.
func (o *FrontPortMapping) GetRearPort() int32 {
	if o == nil || IsNil(o.RearPort) {
		var ret int32
		return ret
	}
	return *o.RearPort
}

// GetRearPortOk returns a tuple with the RearPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FrontPortMapping) GetRearPortOk() (*int32, bool) {
	if o == nil || IsNil(o.RearPort) {
		return nil, false
	}
	return o.RearPort, true
}

// HasRearPort returns a boolean if a field has been set.
func (o *FrontPortMapping) HasRearPort() bool {
	if o != nil && !IsNil(o.RearPort) {
		return true
	}

	return false
}

// SetRearPort gets a reference to the given int32 and assigns it to the RearPort field.
func (o *FrontPortMapping) SetRearPort(v int32) {
	o.RearPort = &v
}

// GetRearPortPosition returns the RearPortPosition field value if set, zero value otherwise.
func (o *FrontPortMapping) GetRearPortPosition() int32 {
	if o == nil || IsNil(o.RearPortPosition) {
		var ret int32
		return ret
	}
	return *o.RearPortPosition
}

// GetRearPortPositionOk returns a tuple with the RearPortPosition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FrontPortMapping) GetRearPortPositionOk() (*int32, bool) {
	if o == nil || IsNil(o.RearPortPosition) {
		return nil, false
	}
	return o.RearPortPosition, true
}

// HasRearPortPosition returns a boolean if a field has been set.
func (o *FrontPortMapping) HasRearPortPosition() bool {
	if o != nil && !IsNil(o.RearPortPosition) {
		return true
	}

	return false
}

// SetRearPortPosition gets a reference to the given int32 and assigns it to the RearPortPosition field.
func (o *FrontPortMapping) SetRearPortPosition(v int32) {
	o.RearPortPosition = &v
}

func (o FrontPortMapping) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FrontPortMapping) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.RearPort) {
		toSerialize["rear_port"] = o.RearPort
	}
	if !IsNil(o.RearPortPosition) {
		toSerialize["rear_port_position"] = o.RearPortPosition
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FrontPortMapping) UnmarshalJSON(data []byte) (err error) {
	varFrontPortMapping := _FrontPortMapping{}

	err = json.Unmarshal(data, &varFrontPortMapping)

	if err != nil {
		return err
	}

	*o = FrontPortMapping(varFrontPortMapping)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "position")
		delete(additionalProperties, "rear_port")
		delete(additionalProperties, "rear_port_position")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFrontPortMapping struct {
	value *FrontPortMapping
	isSet bool
}

func (v NullableFrontPortMapping) Get() *FrontPortMapping {
	return v.value
}

func (v *NullableFrontPortMapping) Set(val *FrontPortMapping) {
	v.value = val
	v.isSet = true
}

func (v NullableFrontPortMapping) IsSet() bool {
	return v.isSet
}

func (v *NullableFrontPortMapping) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFrontPortMapping(val *FrontPortMapping) *NullableFrontPortMapping {
	return &NullableFrontPortMapping{value: val, isSet: true}
}

func (v NullableFrontPortMapping) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFrontPortMapping) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
