// Code generated by openapi-generator from the NetBox 4.7.0 OpenAPI document. DO NOT EDIT.

/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.0 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the VLANTranslationRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VLANTranslationRule{}

// VLANTranslationRule Adds support for custom fields and tags.
type VLANTranslationRule struct {
	Id      int32   `json:"id"`
	Url     *string `json:"url,omitempty"`
	Display *string `json:"display,omitempty"`
	Policy  *int32  `json:"policy,omitempty"`
	// Numeric VLAN ID (1-4094)
	LocalVid *int32 `json:"local_vid,omitempty"`
	// Numeric VLAN ID (1-4094)
	RemoteVid            *int32  `json:"remote_vid,omitempty"`
	Description          *string `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _VLANTranslationRule VLANTranslationRule

// NewVLANTranslationRule instantiates a new VLANTranslationRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVLANTranslationRule(id int32) *VLANTranslationRule {
	this := VLANTranslationRule{}
	this.Id = id
	return &this
}

// NewVLANTranslationRuleWithDefaults instantiates a new VLANTranslationRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVLANTranslationRuleWithDefaults() *VLANTranslationRule {
	this := VLANTranslationRule{}
	return &this
}

// GetId returns the Id field value
func (o *VLANTranslationRule) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *VLANTranslationRule) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *VLANTranslationRule) SetId(v int32) {
	o.Id = v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *VLANTranslationRule) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VLANTranslationRule) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *VLANTranslationRule) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *VLANTranslationRule) SetUrl(v string) {
	o.Url = &v
}

// GetDisplay returns the Display field value if set, zero value otherwise.
func (o *VLANTranslationRule) GetDisplay() string {
	if o == nil || IsNil(o.Display) {
		var ret string
		return ret
	}
	return *o.Display
}

// GetDisplayOk returns a tuple with the Display field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VLANTranslationRule) GetDisplayOk() (*string, bool) {
	if o == nil || IsNil(o.Display) {
		return nil, false
	}
	return o.Display, true
}

// HasDisplay returns a boolean if a field has been set.
func (o *VLANTranslationRule) HasDisplay() bool {
	if o != nil && !IsNil(o.Display) {
		return true
	}

	return false
}

// SetDisplay gets a reference to the given string and assigns it to the Display field.
func (o *VLANTranslationRule) SetDisplay(v string) {
	o.Display = &v
}

// GetPolicy returns the Policy field value if set, zero value otherwise.
func (o *VLANTranslationRule) GetPolicy() int32 {
	if o == nil || IsNil(o.Policy) {
		var ret int32
		return ret
	}
	return *o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VLANTranslationRule) GetPolicyOk() (*int32, bool) {
	if o == nil || IsNil(o.Policy) {
		return nil, false
	}
	return o.Policy, true
}

// HasPolicy returns a boolean if a field has been set.
func (o *VLANTranslationRule) HasPolicy() bool {
	if o != nil && !IsNil(o.Policy) {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given int32 and assigns it to the Policy field.
func (o *VLANTranslationRule) SetPolicy(v int32) {
	o.Policy = &v
}

// GetLocalVid returns the LocalVid field value if set, zero value otherwise.
func (o *VLANTranslationRule) GetLocalVid() int32 {
	if o == nil || IsNil(o.LocalVid) {
		var ret int32
		return ret
	}
	return *o.LocalVid
}

// GetLocalVidOk returns a tuple with the LocalVid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VLANTranslationRule) GetLocalVidOk() (*int32, bool) {
	if o == nil || IsNil(o.LocalVid) {
		return nil, false
	}
	return o.LocalVid, true
}

// HasLocalVid returns a boolean if a field has been set.
func (o *VLANTranslationRule) HasLocalVid() bool {
	if o != nil && !IsNil(o.LocalVid) {
		return true
	}

	return false
}

// SetLocalVid gets a reference to the given int32 and assigns it to the LocalVid field.
func (o *VLANTranslationRule) SetLocalVid(v int32) {
	o.LocalVid = &v
}

// GetRemoteVid returns the RemoteVid field value if set, zero value otherwise.
func (o *VLANTranslationRule) GetRemoteVid() int32 {
	if o == nil || IsNil(o.RemoteVid) {
		var ret int32
		return ret
	}
	return *o.RemoteVid
}

// GetRemoteVidOk returns a tuple with the RemoteVid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VLANTranslationRule) GetRemoteVidOk() (*int32, bool) {
	if o == nil || IsNil(o.RemoteVid) {
		return nil, false
	}
	return o.RemoteVid, true
}

// HasRemoteVid returns a boolean if a field has been set.
func (o *VLANTranslationRule) HasRemoteVid() bool {
	if o != nil && !IsNil(o.RemoteVid) {
		return true
	}

	return false
}

// SetRemoteVid gets a reference to the given int32 and assigns it to the RemoteVid field.
func (o *VLANTranslationRule) SetRemoteVid(v int32) {
	o.RemoteVid = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *VLANTranslationRule) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VLANTranslationRule) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *VLANTranslationRule) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *VLANTranslationRule) SetDescription(v string) {
	o.Description = &v
}

func (o VLANTranslationRule) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VLANTranslationRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Display) {
		toSerialize["display"] = o.Display
	}
	if !IsNil(o.Policy) {
		toSerialize["policy"] = o.Policy
	}
	if !IsNil(o.LocalVid) {
		toSerialize["local_vid"] = o.LocalVid
	}
	if !IsNil(o.RemoteVid) {
		toSerialize["remote_vid"] = o.RemoteVid
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VLANTranslationRule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varVLANTranslationRule := _VLANTranslationRule{}

	err = json.Unmarshal(data, &varVLANTranslationRule)

	if err != nil {
		return err
	}

	*o = VLANTranslationRule(varVLANTranslationRule)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "url")
		delete(additionalProperties, "display")
		delete(additionalProperties, "policy")
		delete(additionalProperties, "local_vid")
		delete(additionalProperties, "remote_vid")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVLANTranslationRule struct {
	value *VLANTranslationRule
	isSet bool
}

func (v NullableVLANTranslationRule) Get() *VLANTranslationRule {
	return v.value
}

func (v *NullableVLANTranslationRule) Set(val *VLANTranslationRule) {
	v.value = val
	v.isSet = true
}

func (v NullableVLANTranslationRule) IsSet() bool {
	return v.isSet
}

func (v *NullableVLANTranslationRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVLANTranslationRule(val *VLANTranslationRule) *NullableVLANTranslationRule {
	return &NullableVLANTranslationRule{value: val, isSet: true}
}

func (v NullableVLANTranslationRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVLANTranslationRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
