// Code generated by openapi-generator from the NetBox 4.7.0 OpenAPI document. DO NOT EDIT.

/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.0 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the RenderedConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RenderedConfig{}

// RenderedConfig Describes the JSON response returned by the /render-config/ and /render/ endpoints.
type RenderedConfig struct {
	Configtemplate *BriefConfigTemplate `json:"configtemplate,omitempty"`
	// The rendered template output.
	Content              *string `json:"content,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RenderedConfig RenderedConfig

// NewRenderedConfig instantiates a new RenderedConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRenderedConfig() *RenderedConfig {
	this := RenderedConfig{}
	return &this
}

// NewRenderedConfigWithDefaults instantiates a new RenderedConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRenderedConfigWithDefaults() *RenderedConfig {
	this := RenderedConfig{}
	return &this
}

// GetConfigtemplate returns the Configtemplate field value if set, zero value otherwise.
func (o *RenderedConfig) GetConfigtemplate() BriefConfigTemplate {
	if o == nil || IsNil(o.Configtemplate) {
		var ret BriefConfigTemplate
		return ret
	}
	return *o.Configtemplate
}

// GetConfigtemplateOk returns a tuple with the Configtemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RenderedConfig) GetConfigtemplateOk() (*BriefConfigTemplate, bool) {
	if o == nil || IsNil(o.Configtemplate) {
		return nil, false
	}
	return o.Configtemplate, true
}

// HasConfigtemplate returns a boolean if a field has been set.
func (o *RenderedConfig) HasConfigtemplate() bool {
	if o != nil && !IsNil(o.Configtemplate) {
		return true
	}

	return false
}

// SetConfigtemplate gets a reference to the given BriefConfigTemplate and assigns it to the Configtemplate field.
func (o *RenderedConfig) SetConfigtemplate(v BriefConfigTemplate) {
	o.Configtemplate = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *RenderedConfig) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RenderedConfig) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *RenderedConfig) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *RenderedConfig) SetContent(v string) {
	o.Content = &v
}

func (o RenderedConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RenderedConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Configtemplate) {
		toSerialize["configtemplate"] = o.Configtemplate
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RenderedConfig) UnmarshalJSON(data []byte) (err error) {
	varRenderedConfig := _RenderedConfig{}

	err = json.Unmarshal(data, &varRenderedConfig)

	if err != nil {
		return err
	}

	*o = RenderedConfig(varRenderedConfig)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "configtemplate")
		delete(additionalProperties, "content")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRenderedConfig struct {
	value *RenderedConfig
	isSet bool
}

func (v NullableRenderedConfig) Get() *RenderedConfig {
	return v.value
}

func (v *NullableRenderedConfig) Set(val *RenderedConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableRenderedConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableRenderedConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRenderedConfig(val *RenderedConfig) *NullableRenderedConfig {
	return &NullableRenderedConfig{value: val, isSet: true}
}

func (v NullableRenderedConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRenderedConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
