// Code generated by openapi-generator from the NetBox 4.7.0 OpenAPI document. DO NOT EDIT.

/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.0 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the BriefCircuitGroupAssignmentSerializer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BriefCircuitGroupAssignmentSerializer{}

// BriefCircuitGroupAssignmentSerializer Base serializer for group assignments under CircuitSerializer.
type BriefCircuitGroupAssignmentSerializer struct {
	Id                   int32              `json:"id"`
	Url                  *string            `json:"url,omitempty"`
	Display              *string            `json:"display,omitempty"`
	Group                *BriefCircuitGroup `json:"group,omitempty"`
	Priority             *ChoiceString      `json:"priority,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BriefCircuitGroupAssignmentSerializer BriefCircuitGroupAssignmentSerializer

// NewBriefCircuitGroupAssignmentSerializer instantiates a new BriefCircuitGroupAssignmentSerializer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBriefCircuitGroupAssignmentSerializer(id int32) *BriefCircuitGroupAssignmentSerializer {
	this := BriefCircuitGroupAssignmentSerializer{}
	this.Id = id
	return &this
}

// NewBriefCircuitGroupAssignmentSerializerWithDefaults instantiates a new BriefCircuitGroupAssignmentSerializer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBriefCircuitGroupAssignmentSerializerWithDefaults() *BriefCircuitGroupAssignmentSerializer {
	this := BriefCircuitGroupAssignmentSerializer{}
	return &this
}

// GetId returns the Id field value
func (o *BriefCircuitGroupAssignmentSerializer) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BriefCircuitGroupAssignmentSerializer) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BriefCircuitGroupAssignmentSerializer) SetId(v int32) {
	o.Id = v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *BriefCircuitGroupAssignmentSerializer) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefCircuitGroupAssignmentSerializer) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *BriefCircuitGroupAssignmentSerializer) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *BriefCircuitGroupAssignmentSerializer) SetUrl(v string) {
	o.Url = &v
}

// GetDisplay returns the Display field value if set, zero value otherwise.
func (o *BriefCircuitGroupAssignmentSerializer) GetDisplay() string {
	if o == nil || IsNil(o.Display) {
		var ret string
		return ret
	}
	return *o.Display
}

// GetDisplayOk returns a tuple with the Display field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefCircuitGroupAssignmentSerializer) GetDisplayOk() (*string, bool) {
	if o == nil || IsNil(o.Display) {
		return nil, false
	}
	return o.Display, true
}

// HasDisplay returns a boolean if a field has been set.
func (o *BriefCircuitGroupAssignmentSerializer) HasDisplay() bool {
	if o != nil && !IsNil(o.Display) {
		return true
	}

	return false
}

// SetDisplay gets a reference to the given string and assigns it to the Display field.
func (o *BriefCircuitGroupAssignmentSerializer) SetDisplay(v string) {
	o.Display = &v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *BriefCircuitGroupAssignmentSerializer) GetGroup() BriefCircuitGroup {
	if o == nil || IsNil(o.Group) {
		var ret BriefCircuitGroup
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefCircuitGroupAssignmentSerializer) GetGroupOk() (*BriefCircuitGroup, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *BriefCircuitGroupAssignmentSerializer) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given BriefCircuitGroup and assigns it to the Group field.
func (o *BriefCircuitGroupAssignmentSerializer) SetGroup(v BriefCircuitGroup) {
	o.Group = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *BriefCircuitGroupAssignmentSerializer) GetPriority() ChoiceString {
	if o == nil || IsNil(o.Priority) {
		var ret ChoiceString
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefCircuitGroupAssignmentSerializer) GetPriorityOk() (*ChoiceString, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *BriefCircuitGroupAssignmentSerializer) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given ChoiceString and assigns it to the Priority field.
func (o *BriefCircuitGroupAssignmentSerializer) SetPriority(v ChoiceString) {
	o.Priority = &v
}

func (o BriefCircuitGroupAssignmentSerializer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BriefCircuitGroupAssignmentSerializer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Display) {
		toSerialize["display"] = o.Display
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BriefCircuitGroupAssignmentSerializer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varBriefCircuitGroupAssignmentSerializer := _BriefCircuitGroupAssignmentSerializer{}

	err = json.Unmarshal(data, &varBriefCircuitGroupAssignmentSerializer)

	if err != nil {
		return err
	}

	*o = BriefCircuitGroupAssignmentSerializer(varBriefCircuitGroupAssignmentSerializer)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "url")
		delete(additionalProperties, "display")
		delete(additionalProperties, "group")
		delete(additionalProperties, "priority")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBriefCircuitGroupAssignmentSerializer struct {
	value *BriefCircuitGroupAssignmentSerializer
	isSet bool
}

func (v NullableBriefCircuitGroupAssignmentSerializer) Get() *BriefCircuitGroupAssignmentSerializer {
	return v.value
}

func (v *NullableBriefCircuitGroupAssignmentSerializer) Set(val *BriefCircuitGroupAssignmentSerializer) {
	v.value = val
	v.isSet = true
}

func (v NullableBriefCircuitGroupAssignmentSerializer) IsSet() bool {
	return v.isSet
}

func (v *NullableBriefCircuitGroupAssignmentSerializer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBriefCircuitGroupAssignmentSerializer(val *BriefCircuitGroupAssignmentSerializer) *NullableBriefCircuitGroupAssignmentSerializer {
	return &NullableBriefCircuitGroupAssignmentSerializer{value: val, isSet: true}
}

func (v NullableBriefCircuitGroupAssignmentSerializer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBriefCircuitGroupAssignmentSerializer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
