// Code generated by openapi-generator from the NetBox 4.7.0 OpenAPI document. DO NOT EDIT.

/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.0 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the RackUnit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RackUnit{}

// RackUnit A rack unit is an abstraction formed by the set (rack, position, face); it does not exist as a row in the database.
type RackUnit struct {
	Id                   float64       `json:"id"`
	Name                 *string       `json:"name,omitempty"`
	Face                 *ChoiceString `json:"face,omitempty"`
	Device               *BriefDevice  `json:"device,omitempty"`
	Occupied             *bool         `json:"occupied,omitempty"`
	Display              *string       `json:"display,omitempty"`
	Description          *string       `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RackUnit RackUnit

// NewRackUnit instantiates a new RackUnit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRackUnit(id float64) *RackUnit {
	this := RackUnit{}
	this.Id = id
	return &this
}

// NewRackUnitWithDefaults instantiates a new RackUnit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRackUnitWithDefaults() *RackUnit {
	this := RackUnit{}
	return &this
}

// GetId returns the Id field value
func (o *RackUnit) GetId() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RackUnit) GetIdOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RackUnit) SetId(v float64) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RackUnit) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RackUnit) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RackUnit) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RackUnit) SetName(v string) {
	o.Name = &v
}

// GetFace returns the Face field value if set, zero value otherwise.
func (o *RackUnit) GetFace() ChoiceString {
	if o == nil || IsNil(o.Face) {
		var ret ChoiceString
		return ret
	}
	return *o.Face
}

// GetFaceOk returns a tuple with the Face field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RackUnit) GetFaceOk() (*ChoiceString, bool) {
	if o == nil || IsNil(o.Face) {
		return nil, false
	}
	return o.Face, true
}

// HasFace returns a boolean if a field has been set.
func (o *RackUnit) HasFace() bool {
	if o != nil && !IsNil(o.Face) {
		return true
	}

	return false
}

// SetFace gets a reference to the given ChoiceString and assigns it to the Face field.
func (o *RackUnit) SetFace(v ChoiceString) {
	o.Face = &v
}

// GetDevice returns the Device field value if set, zero value otherwise.
func (o *RackUnit) GetDevice() BriefDevice {
	if o == nil || IsNil(o.Device) {
		var ret BriefDevice
		return ret
	}
	return *o.Device
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RackUnit) GetDeviceOk() (*BriefDevice, bool) {
	if o == nil || IsNil(o.Device) {
		return nil, false
	}
	return o.Device, true
}

// HasDevice returns a boolean if a field has been set.
func (o *RackUnit) HasDevice() bool {
	if o != nil && !IsNil(o.Device) {
		return true
	}

	return false
}

// SetDevice gets a reference to the given BriefDevice and assigns it to the Device field.
func (o *RackUnit) SetDevice(v BriefDevice) {
	o.Device = &v
}

// GetOccupied returns the Occupied field value if set, zero value otherwise.
func (o *RackUnit) GetOccupied() bool {
	if o == nil || IsNil(o.Occupied) {
		var ret bool
		return ret
	}
	return *o.Occupied
}

// GetOccupiedOk returns a tuple with the Occupied field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RackUnit) GetOccupiedOk() (*bool, bool) {
	if o == nil || IsNil(o.Occupied) {
		return nil, false
	}
	return o.Occupied, true
}

// HasOccupied returns a boolean if a field has been set.
func (o *RackUnit) HasOccupied() bool {
	if o != nil && !IsNil(o.Occupied) {
		return true
	}

	return false
}

// SetOccupied gets a reference to the given bool and assigns it to the Occupied field.
func (o *RackUnit) SetOccupied(v bool) {
	o.Occupied = &v
}

// GetDisplay returns the Display field value if set, zero value otherwise.
func (o *RackUnit) GetDisplay() string {
	if o == nil || IsNil(o.Display) {
		var ret string
		return ret
	}
	return *o.Display
}

// GetDisplayOk returns a tuple with the Display field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RackUnit) GetDisplayOk() (*string, bool) {
	if o == nil || IsNil(o.Display) {
		return nil, false
	}
	return o.Display, true
}

// HasDisplay returns a boolean if a field has been set.
func (o *RackUnit) HasDisplay() bool {
	if o != nil && !IsNil(o.Display) {
		return true
	}

	return false
}

// SetDisplay gets a reference to the given string and assigns it to the Display field.
func (o *RackUnit) SetDisplay(v string) {
	o.Display = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RackUnit) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RackUnit) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RackUnit) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RackUnit) SetDescription(v string) {
	o.Description = &v
}

func (o RackUnit) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RackUnit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Face) {
		toSerialize["face"] = o.Face
	}
	if !IsNil(o.Device) {
		toSerialize["device"] = o.Device
	}
	if !IsNil(o.Occupied) {
		toSerialize["occupied"] = o.Occupied
	}
	if !IsNil(o.Display) {
		toSerialize["display"] = o.Display
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RackUnit) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varRackUnit := _RackUnit{}

	err = json.Unmarshal(data, &varRackUnit)

	if err != nil {
		return err
	}

	*o = RackUnit(varRackUnit)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "face")
		delete(additionalProperties, "device")
		delete(additionalProperties, "occupied")
		delete(additionalProperties, "display")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRackUnit struct {
	value *RackUnit
	isSet bool
}

func (v NullableRackUnit) Get() *RackUnit {
	return v.value
}

func (v *NullableRackUnit) Set(val *RackUnit) {
	v.value = val
	v.isSet = true
}

func (v NullableRackUnit) IsSet() bool {
	return v.isSet
}

func (v *NullableRackUnit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRackUnit(val *RackUnit) *NullableRackUnit {
	return &NullableRackUnit{value: val, isSet: true}
}

func (v NullableRackUnit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRackUnit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
