// Code generated by openapi-generator from the NetBox 4.7.0 OpenAPI document. DO NOT EDIT.

/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.0 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the BackgroundTask type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackgroundTask{}

// BackgroundTask struct for BackgroundTask
type BackgroundTask struct {
	Id                   string                 `json:"id"`
	Url                  *string                `json:"url,omitempty"`
	Description          *string                `json:"description,omitempty"`
	Origin               *string                `json:"origin,omitempty"`
	FuncName             *string                `json:"func_name,omitempty"`
	Args                 []interface{}          `json:"args,omitempty"`
	Kwargs               map[string]interface{} `json:"kwargs,omitempty"`
	Result               *string                `json:"result,omitempty"`
	Timeout              *int32                 `json:"timeout,omitempty"`
	ResultTtl            *int32                 `json:"result_ttl,omitempty"`
	CreatedAt            *time.Time             `json:"created_at,omitempty"`
	EnqueuedAt           *time.Time             `json:"enqueued_at,omitempty"`
	StartedAt            *time.Time             `json:"started_at,omitempty"`
	EndedAt              *time.Time             `json:"ended_at,omitempty"`
	WorkerName           *string                `json:"worker_name,omitempty"`
	Position             *int32                 `json:"position,omitempty"`
	Status               *string                `json:"status,omitempty"`
	Meta                 map[string]interface{} `json:"meta,omitempty"`
	LastHeartbeat        *string                `json:"last_heartbeat,omitempty"`
	IsFinished           *bool                  `json:"is_finished,omitempty"`
	IsQueued             *bool                  `json:"is_queued,omitempty"`
	IsFailed             *bool                  `json:"is_failed,omitempty"`
	IsStarted            *bool                  `json:"is_started,omitempty"`
	IsDeferred           *bool                  `json:"is_deferred,omitempty"`
	IsCanceled           *bool                  `json:"is_canceled,omitempty"`
	IsScheduled          *bool                  `json:"is_scheduled,omitempty"`
	IsStopped            *bool                  `json:"is_stopped,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BackgroundTask BackgroundTask

// NewBackgroundTask instantiates a new BackgroundTask object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackgroundTask(id string) *BackgroundTask {
	this := BackgroundTask{}
	this.Id = id
	return &this
}

// NewBackgroundTaskWithDefaults instantiates a new BackgroundTask object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackgroundTaskWithDefaults() *BackgroundTask {
	this := BackgroundTask{}
	return &this
}

// GetId returns the Id field value
func (o *BackgroundTask) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BackgroundTask) SetId(v string) {
	o.Id = v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *BackgroundTask) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *BackgroundTask) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *BackgroundTask) SetUrl(v string) {
	o.Url = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *BackgroundTask) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *BackgroundTask) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *BackgroundTask) SetDescription(v string) {
	o.Description = &v
}

// GetOrigin returns the Origin field value if set, zero value otherwise.
func (o *BackgroundTask) GetOrigin() string {
	if o == nil || IsNil(o.Origin) {
		var ret string
		return ret
	}
	return *o.Origin
}

// GetOriginOk returns a tuple with the Origin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetOriginOk() (*string, bool) {
	if o == nil || IsNil(o.Origin) {
		return nil, false
	}
	return o.Origin, true
}

// HasOrigin returns a boolean if a field has been set.
func (o *BackgroundTask) HasOrigin() bool {
	if o != nil && !IsNil(o.Origin) {
		return true
	}

	return false
}

// SetOrigin gets a reference to the given string and assigns it to the Origin field.
func (o *BackgroundTask) SetOrigin(v string) {
	o.Origin = &v
}

// GetFuncName returns the FuncName field value if set, zero value otherwise.
func (o *BackgroundTask) GetFuncName() string {
	if o == nil || IsNil(o.FuncName) {
		var ret string
		return ret
	}
	return *o.FuncName
}

// GetFuncNameOk returns a tuple with the FuncName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetFuncNameOk() (*string, bool) {
	if o == nil || IsNil(o.FuncName) {
		return nil, false
	}
	return o.FuncName, true
}

// HasFuncName returns a boolean if a field has been set.
func (o *BackgroundTask) HasFuncName() bool {
	if o != nil && !IsNil(o.FuncName) {
		return true
	}

	return false
}

// SetFuncName gets a reference to the given string and assigns it to the FuncName field.
func (o *BackgroundTask) SetFuncName(v string) {
	o.FuncName = &v
}

// GetArgs returns the Args field value if set, zero value otherwise.
func (o *BackgroundTask) GetArgs() []interface{} {
	if o == nil || IsNil(o.Args) {
		var ret []interface{}
		return ret
	}
	return o.Args
}

// GetArgsOk returns a tuple with the Args field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetArgsOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Args) {
		return nil, false
	}
	return o.Args, true
}

// HasArgs returns a boolean if a field has been set.
func (o *BackgroundTask) HasArgs() bool {
	if o != nil && !IsNil(o.Args) {
		return true
	}

	return false
}

// SetArgs gets a reference to the given []interface{} and assigns it to the Args field.
func (o *BackgroundTask) SetArgs(v []interface{}) {
	o.Args = v
}

// GetKwargs returns the Kwargs field value if set, zero value otherwise.
func (o *BackgroundTask) GetKwargs() map[string]interface{} {
	if o == nil || IsNil(o.Kwargs) {
		var ret map[string]interface{}
		return ret
	}
	return o.Kwargs
}

// GetKwargsOk returns a tuple with the Kwargs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetKwargsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Kwargs) {
		return map[string]interface{}{}, false
	}
	return o.Kwargs, true
}

// HasKwargs returns a boolean if a field has been set.
func (o *BackgroundTask) HasKwargs() bool {
	if o != nil && !IsNil(o.Kwargs) {
		return true
	}

	return false
}

// SetKwargs gets a reference to the given map[string]interface{} and assigns it to the Kwargs field.
func (o *BackgroundTask) SetKwargs(v map[string]interface{}) {
	o.Kwargs = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *BackgroundTask) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *BackgroundTask) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *BackgroundTask) SetResult(v string) {
	o.Result = &v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *BackgroundTask) GetTimeout() int32 {
	if o == nil || IsNil(o.Timeout) {
		var ret int32
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *BackgroundTask) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given int32 and assigns it to the Timeout field.
func (o *BackgroundTask) SetTimeout(v int32) {
	o.Timeout = &v
}

// GetResultTtl returns the ResultTtl field value if set, zero value otherwise.
func (o *BackgroundTask) GetResultTtl() int32 {
	if o == nil || IsNil(o.ResultTtl) {
		var ret int32
		return ret
	}
	return *o.ResultTtl
}

// GetResultTtlOk returns a tuple with the ResultTtl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetResultTtlOk() (*int32, bool) {
	if o == nil || IsNil(o.ResultTtl) {
		return nil, false
	}
	return o.ResultTtl, true
}

// HasResultTtl returns a boolean if a field has been set.
func (o *BackgroundTask) HasResultTtl() bool {
	if o != nil && !IsNil(o.ResultTtl) {
		return true
	}

	return false
}

// SetResultTtl gets a reference to the given int32 and assigns it to the ResultTtl field.
func (o *BackgroundTask) SetResultTtl(v int32) {
	o.ResultTtl = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *BackgroundTask) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *BackgroundTask) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *BackgroundTask) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetEnqueuedAt returns the EnqueuedAt field value if set, zero value otherwise.
func (o *BackgroundTask) GetEnqueuedAt() time.Time {
	if o == nil || IsNil(o.EnqueuedAt) {
		var ret time.Time
		return ret
	}
	return *o.EnqueuedAt
}

// GetEnqueuedAtOk returns a tuple with the EnqueuedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetEnqueuedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EnqueuedAt) {
		return nil, false
	}
	return o.EnqueuedAt, true
}

// HasEnqueuedAt returns a boolean if a field has been set.
func (o *BackgroundTask) HasEnqueuedAt() bool {
	if o != nil && !IsNil(o.EnqueuedAt) {
		return true
	}

	return false
}

// SetEnqueuedAt gets a reference to the given time.Time and assigns it to the EnqueuedAt field.
func (o *BackgroundTask) SetEnqueuedAt(v time.Time) {
	o.EnqueuedAt = &v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *BackgroundTask) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetStartedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *BackgroundTask) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given time.Time and assigns it to the StartedAt field.
func (o *BackgroundTask) SetStartedAt(v time.Time) {
	o.StartedAt = &v
}

// GetEndedAt returns the EndedAt field value if set, zero value otherwise.
func (o *BackgroundTask) GetEndedAt() time.Time {
	if o == nil || IsNil(o.EndedAt) {
		var ret time.Time
		return ret
	}
	return *o.EndedAt
}

// GetEndedAtOk returns a tuple with the EndedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetEndedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndedAt) {
		return nil, false
	}
	return o.EndedAt, true
}

// HasEndedAt returns a boolean if a field has been set.
func (o *BackgroundTask) HasEndedAt() bool {
	if o != nil && !IsNil(o.EndedAt) {
		return true
	}

	return false
}

// SetEndedAt gets a reference to the given time.Time and assigns it to the EndedAt field.
func (o *BackgroundTask) SetEndedAt(v time.Time) {
	o.EndedAt = &v
}

// GetWorkerName returns the WorkerName field value if set, zero value otherwise.
func (o *BackgroundTask) GetWorkerName() string {
	if o == nil || IsNil(o.WorkerName) {
		var ret string
		return ret
	}
	return *o.WorkerName
}

// GetWorkerNameOk returns a tuple with the WorkerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetWorkerNameOk() (*string, bool) {
	if o == nil || IsNil(o.WorkerName) {
		return nil, false
	}
	return o.WorkerName, true
}

// HasWorkerName returns a boolean if a field has been set.
func (o *BackgroundTask) HasWorkerName() bool {
	if o != nil && !IsNil(o.WorkerName) {
		return true
	}

	return false
}

// SetWorkerName gets a reference to the given string and assigns it to the WorkerName field.
func (o *BackgroundTask) SetWorkerName(v string) {
	o.WorkerName = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *BackgroundTask) GetPosition() int32 {
	if o == nil || IsNil(o.Position) {
		var ret int32
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetPositionOk() (*int32, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *BackgroundTask) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int32 and assigns it to the Position field.
func (o *BackgroundTask) SetPosition(v int32) {
	o.Position = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BackgroundTask) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BackgroundTask) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *BackgroundTask) SetStatus(v string) {
	o.Status = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *BackgroundTask) GetMeta() map[string]interface{} {
	if o == nil || IsNil(o.Meta) {
		var ret map[string]interface{}
		return ret
	}
	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Meta) {
		return map[string]interface{}{}, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *BackgroundTask) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given map[string]interface{} and assigns it to the Meta field.
func (o *BackgroundTask) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

// GetLastHeartbeat returns the LastHeartbeat field value if set, zero value otherwise.
func (o *BackgroundTask) GetLastHeartbeat() string {
	if o == nil || IsNil(o.LastHeartbeat) {
		var ret string
		return ret
	}
	return *o.LastHeartbeat
}

// GetLastHeartbeatOk returns a tuple with the LastHeartbeat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetLastHeartbeatOk() (*string, bool) {
	if o == nil || IsNil(o.LastHeartbeat) {
		return nil, false
	}
	return o.LastHeartbeat, true
}

// HasLastHeartbeat returns a boolean if a field has been set.
func (o *BackgroundTask) HasLastHeartbeat() bool {
	if o != nil && !IsNil(o.LastHeartbeat) {
		return true
	}

	return false
}

// SetLastHeartbeat gets a reference to the given string and assigns it to the LastHeartbeat field.
func (o *BackgroundTask) SetLastHeartbeat(v string) {
	o.LastHeartbeat = &v
}

// GetIsFinished returns the IsFinished field value if set, zero value otherwise.
func (o *BackgroundTask) GetIsFinished() bool {
	if o == nil || IsNil(o.IsFinished) {
		var ret bool
		return ret
	}
	return *o.IsFinished
}

// GetIsFinishedOk returns a tuple with the IsFinished field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetIsFinishedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsFinished) {
		return nil, false
	}
	return o.IsFinished, true
}

// HasIsFinished returns a boolean if a field has been set.
func (o *BackgroundTask) HasIsFinished() bool {
	if o != nil && !IsNil(o.IsFinished) {
		return true
	}

	return false
}

// SetIsFinished gets a reference to the given bool and assigns it to the IsFinished field.
func (o *BackgroundTask) SetIsFinished(v bool) {
	o.IsFinished = &v
}

// GetIsQueued returns the IsQueued field value if set, zero value otherwise.
func (o *BackgroundTask) GetIsQueued() bool {
	if o == nil || IsNil(o.IsQueued) {
		var ret bool
		return ret
	}
	return *o.IsQueued
}

// GetIsQueuedOk returns a tuple with the IsQueued field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetIsQueuedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsQueued) {
		return nil, false
	}
	return o.IsQueued, true
}

// HasIsQueued returns a boolean if a field has been set.
func (o *BackgroundTask) HasIsQueued() bool {
	if o != nil && !IsNil(o.IsQueued) {
		return true
	}

	return false
}

// SetIsQueued gets a reference to the given bool and assigns it to the IsQueued field.
func (o *BackgroundTask) SetIsQueued(v bool) {
	o.IsQueued = &v
}

// GetIsFailed returns the IsFailed field value if set, zero value otherwise.
func (o *BackgroundTask) GetIsFailed() bool {
	if o == nil || IsNil(o.IsFailed) {
		var ret bool
		return ret
	}
	return *o.IsFailed
}

// GetIsFailedOk returns a tuple with the IsFailed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetIsFailedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsFailed) {
		return nil, false
	}
	return o.IsFailed, true
}

// HasIsFailed returns a boolean if a field has been set.
func (o *BackgroundTask) HasIsFailed() bool {
	if o != nil && !IsNil(o.IsFailed) {
		return true
	}

	return false
}

// SetIsFailed gets a reference to the given bool and assigns it to the IsFailed field.
func (o *BackgroundTask) SetIsFailed(v bool) {
	o.IsFailed = &v
}

// GetIsStarted returns the IsStarted field value if set, zero value otherwise.
func (o *BackgroundTask) GetIsStarted() bool {
	if o == nil || IsNil(o.IsStarted) {
		var ret bool
		return ret
	}
	return *o.IsStarted
}

// GetIsStartedOk returns a tuple with the IsStarted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetIsStartedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsStarted) {
		return nil, false
	}
	return o.IsStarted, true
}

// HasIsStarted returns a boolean if a field has been set.
func (o *BackgroundTask) HasIsStarted() bool {
	if o != nil && !IsNil(o.IsStarted) {
		return true
	}

	return false
}

// SetIsStarted gets a reference to the given bool and assigns it to the IsStarted field.
func (o *BackgroundTask) SetIsStarted(v bool) {
	o.IsStarted = &v
}

// GetIsDeferred returns the IsDeferred field value if set, zero value otherwise.
func (o *BackgroundTask) GetIsDeferred() bool {
	if o == nil || IsNil(o.IsDeferred) {
		var ret bool
		return ret
	}
	return *o.IsDeferred
}

// GetIsDeferredOk returns a tuple with the IsDeferred field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetIsDeferredOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeferred) {
		return nil, false
	}
	return o.IsDeferred, true
}

// HasIsDeferred returns a boolean if a field has been set.
func (o *BackgroundTask) HasIsDeferred() bool {
	if o != nil && !IsNil(o.IsDeferred) {
		return true
	}

	return false
}

// SetIsDeferred gets a reference to the given bool and assigns it to the IsDeferred field.
func (o *BackgroundTask) SetIsDeferred(v bool) {
	o.IsDeferred = &v
}

// GetIsCanceled returns the IsCanceled field value if set, zero value otherwise.
func (o *BackgroundTask) GetIsCanceled() bool {
	if o == nil || IsNil(o.IsCanceled) {
		var ret bool
		return ret
	}
	return *o.IsCanceled
}

// GetIsCanceledOk returns a tuple with the IsCanceled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetIsCanceledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsCanceled) {
		return nil, false
	}
	return o.IsCanceled, true
}

// HasIsCanceled returns a boolean if a field has been set.
func (o *BackgroundTask) HasIsCanceled() bool {
	if o != nil && !IsNil(o.IsCanceled) {
		return true
	}

	return false
}

// SetIsCanceled gets a reference to the given bool and assigns it to the IsCanceled field.
func (o *BackgroundTask) SetIsCanceled(v bool) {
	o.IsCanceled = &v
}

// GetIsScheduled returns the IsScheduled field value if set, zero value otherwise.
func (o *BackgroundTask) GetIsScheduled() bool {
	if o == nil || IsNil(o.IsScheduled) {
		var ret bool
		return ret
	}
	return *o.IsScheduled
}

// GetIsScheduledOk returns a tuple with the IsScheduled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetIsScheduledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsScheduled) {
		return nil, false
	}
	return o.IsScheduled, true
}

// HasIsScheduled returns a boolean if a field has been set.
func (o *BackgroundTask) HasIsScheduled() bool {
	if o != nil && !IsNil(o.IsScheduled) {
		return true
	}

	return false
}

// SetIsScheduled gets a reference to the given bool and assigns it to the IsScheduled field.
func (o *BackgroundTask) SetIsScheduled(v bool) {
	o.IsScheduled = &v
}

// GetIsStopped returns the IsStopped field value if set, zero value otherwise.
func (o *BackgroundTask) GetIsStopped() bool {
	if o == nil || IsNil(o.IsStopped) {
		var ret bool
		return ret
	}
	return *o.IsStopped
}

// GetIsStoppedOk returns a tuple with the IsStopped field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BackgroundTask) GetIsStoppedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsStopped) {
		return nil, false
	}
	return o.IsStopped, true
}

// HasIsStopped returns a boolean if a field has been set.
func (o *BackgroundTask) HasIsStopped() bool {
	if o != nil && !IsNil(o.IsStopped) {
		return true
	}

	return false
}

// SetIsStopped gets a reference to the given bool and assigns it to the IsStopped field.
func (o *BackgroundTask) SetIsStopped(v bool) {
	o.IsStopped = &v
}

func (o BackgroundTask) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackgroundTask) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Origin) {
		toSerialize["origin"] = o.Origin
	}
	if !IsNil(o.FuncName) {
		toSerialize["func_name"] = o.FuncName
	}
	if !IsNil(o.Args) {
		toSerialize["args"] = o.Args
	}
	if !IsNil(o.Kwargs) {
		toSerialize["kwargs"] = o.Kwargs
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	if !IsNil(o.ResultTtl) {
		toSerialize["result_ttl"] = o.ResultTtl
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.EnqueuedAt) {
		toSerialize["enqueued_at"] = o.EnqueuedAt
	}
	if !IsNil(o.StartedAt) {
		toSerialize["started_at"] = o.StartedAt
	}
	if !IsNil(o.EndedAt) {
		toSerialize["ended_at"] = o.EndedAt
	}
	if !IsNil(o.WorkerName) {
		toSerialize["worker_name"] = o.WorkerName
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.LastHeartbeat) {
		toSerialize["last_heartbeat"] = o.LastHeartbeat
	}
	if !IsNil(o.IsFinished) {
		toSerialize["is_finished"] = o.IsFinished
	}
	if !IsNil(o.IsQueued) {
		toSerialize["is_queued"] = o.IsQueued
	}
	if !IsNil(o.IsFailed) {
		toSerialize["is_failed"] = o.IsFailed
	}
	if !IsNil(o.IsStarted) {
		toSerialize["is_started"] = o.IsStarted
	}
	if !IsNil(o.IsDeferred) {
		toSerialize["is_deferred"] = o.IsDeferred
	}
	if !IsNil(o.IsCanceled) {
		toSerialize["is_canceled"] = o.IsCanceled
	}
	if !IsNil(o.IsScheduled) {
		toSerialize["is_scheduled"] = o.IsScheduled
	}
	if !IsNil(o.IsStopped) {
		toSerialize["is_stopped"] = o.IsStopped
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BackgroundTask) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varBackgroundTask := _BackgroundTask{}

	err = json.Unmarshal(data, &varBackgroundTask)

	if err != nil {
		return err
	}

	*o = BackgroundTask(varBackgroundTask)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "url")
		delete(additionalProperties, "description")
		delete(additionalProperties, "origin")
		delete(additionalProperties, "func_name")
		delete(additionalProperties, "args")
		delete(additionalProperties, "kwargs")
		delete(additionalProperties, "result")
		delete(additionalProperties, "timeout")
		delete(additionalProperties, "result_ttl")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "enqueued_at")
		delete(additionalProperties, "started_at")
		delete(additionalProperties, "ended_at")
		delete(additionalProperties, "worker_name")
		delete(additionalProperties, "position")
		delete(additionalProperties, "status")
		delete(additionalProperties, "meta")
		delete(additionalProperties, "last_heartbeat")
		delete(additionalProperties, "is_finished")
		delete(additionalProperties, "is_queued")
		delete(additionalProperties, "is_failed")
		delete(additionalProperties, "is_started")
		delete(additionalProperties, "is_deferred")
		delete(additionalProperties, "is_canceled")
		delete(additionalProperties, "is_scheduled")
		delete(additionalProperties, "is_stopped")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBackgroundTask struct {
	value *BackgroundTask
	isSet bool
}

func (v NullableBackgroundTask) Get() *BackgroundTask {
	return v.value
}

func (v *NullableBackgroundTask) Set(val *BackgroundTask) {
	v.value = val
	v.isSet = true
}

func (v NullableBackgroundTask) IsSet() bool {
	return v.isSet
}

func (v *NullableBackgroundTask) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackgroundTask(val *BackgroundTask) *NullableBackgroundTask {
	return &NullableBackgroundTask{value: val, isSet: true}
}

func (v NullableBackgroundTask) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackgroundTask) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
