# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_vrfs" "all" {}

data "netbox_vrfs" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "vrfs_ids" {
  value = data.netbox_vrfs.filtered.items[*].id
}
