# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_tag" "example" {
  name = "example-tag"
  slug = "example-tag"
}

resource "netbox_ike_proposal" "example" {
  name = "example"
  authentication_method = "preshared-keys"
  encryption_algorithm = "aes-128-cbc"
  group = 1
  description = "Managed by Terraform"
  tags = [netbox_tag.example.slug]
}
