# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
# netbox_custom_field_choice_set can be imported by its NetBox object ID.
terraform import netbox_custom_field_choice_set.example 123
