# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_manufacturer" "example" {
  name = "example"
  slug = "example"
}
resource "netbox_device_type" "example" {
  manufacturer_id = netbox_manufacturer.example.id
  model           = "example"
  slug            = "example"
}
resource "netbox_device_role" "example" {
  name = "example"
  slug = "example"
}
resource "netbox_site" "example" {
  name = "example"
  slug = "example"
}
resource "netbox_device" "example" {
  name           = "example"
  device_type_id = netbox_device_type.example.id
  role_id        = netbox_device_role.example.id
  site_id        = netbox_site.example.id
}
resource "netbox_interface" "a" {
  device_id = netbox_device.example.id
  name      = "eth0"
  type      = "1000base-t"
}
resource "netbox_interface" "b" {
  device_id = netbox_device.example.id
  name      = "eth1"
  type      = "1000base-t"
}
resource "netbox_cable" "example" {
  a_terminations = [{ object_type = "dcim.interface", object_id = netbox_interface.a.id }]
  b_terminations = [{ object_type = "dcim.interface", object_id = netbox_interface.b.id }]
  type           = "cat6"
  label          = "example"
}
