# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
# netbox_vlan_translation_rule can be imported by its NetBox object ID.
terraform import netbox_vlan_translation_rule.example 123
