# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_vlan_translation_rule" "example" {
  policy_id = netbox_vlan_translation_policy.example.id
  local_vid = 1
  remote_vid = 1
}
