# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
# netbox_fhrp_group_assignment can be imported by its NetBox object ID.
terraform import netbox_fhrp_group_assignment.example 123
