# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_fhrp_group_assignment" "example" {
  group_id = netbox_fhrp_group.example.id
  interface_type = "example"
  interface_id = 1
  priority = 1
}
