# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_circuit_terminations" "all" {}

data "netbox_circuit_terminations" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "circuit_terminations_ids" {
  value = data.netbox_circuit_terminations.filtered.items[*].id
}
