# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_module" "example" {
  device_id = netbox_device.example.id
  module_bay_id = netbox_module_bay.example.id
  module_type_id = netbox_module_type.example.id
}
