# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_vm_interfaces" "all" {}

data "netbox_vm_interfaces" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "vm_interfaces_ids" {
  value = data.netbox_vm_interfaces.filtered.items[*].id
}
