# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_export_template" "example" {
  object_types = []
  name = "example"
  template_code = "example"
}
