# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
# netbox_rack_type can be imported by its NetBox object ID.
terraform import netbox_rack_type.example 123
