# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_services" "all" {}

data "netbox_services" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "services_ids" {
  value = data.netbox_services.filtered.items[*].id
}
