# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_asn_range" "example" {
  name = "example"
  slug = "example"
  rir_id = netbox_rir.example.id
  start = 1
  end = 1
}
