# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_data_source" "example" {
  name = "example"
  type = "example"
  source_url = "example"
  description = "Managed by Terraform"
}
