# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_device_bay_templates" "all" {}

data "netbox_device_bay_templates" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "device_bay_templates_ids" {
  value = data.netbox_device_bay_templates.filtered.items[*].id
}
