# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_wireless_links" "all" {}

data "netbox_wireless_links" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "wireless_links_ids" {
  value = data.netbox_wireless_links.filtered.items[*].id
}
