# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_ipsec_policies" "all" {}

data "netbox_ipsec_policies" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "ipsec_policies_ids" {
  value = data.netbox_ipsec_policies.filtered.items[*].id
}
