# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
# netbox_ip_range can be imported by its NetBox object ID.
terraform import netbox_ip_range.example 123
