# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_scripts" "all" {}

data "netbox_scripts" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "scripts_ids" {
  value = data.netbox_scripts.filtered.items[*].id
}
