# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_virtual_circuit_termination" "example" {
  virtual_circuit_id = netbox_virtual_circuit.example.id
  interface_id = netbox_interface.example.id
}
