# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_vlan" "example" {
  name = "example"
}

# Lookup by arbitrary API filters:
data "netbox_vlan" "filtered" {
  filters = [
    { name = "id", value = "123" },
  ]
}
