# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_tag" "example" {
  name = "example-tag"
  slug = "example-tag"
}

resource "netbox_journal_entry" "example" {
  assigned_object_type = "example"
  assigned_object_id = 1
  comments = "example"
  tags = [netbox_tag.example.slug]
}
