# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_vlans" "all" {}

data "netbox_vlans" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "vlans_ids" {
  value = data.netbox_vlans.filtered.items[*].id
}
