# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_front_port_template" "example" {
  name = "example"
  type = "8p8c"
  description = "Managed by Terraform"
}
