# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_circuit" "example" {
  cid = "example"
  provider_id = netbox_provider.example.id
  type_id = netbox_circuit_type.example.id
}
