# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_tunnel_termination" "example" {
  tunnel_id = netbox_tunnel.example.id
  termination_type = "example"
}
