# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_module_type" "example" {
  manufacturer_id = netbox_manufacturer.example.id
  model = "example"
}
