# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_vlan_group" "example" {
  name       = "example"
  slug       = "example"
  vid_ranges = [[100, 199]]
}
