# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_notification_groups" "all" {}

data "netbox_notification_groups" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "notification_groups_ids" {
  value = data.netbox_notification_groups.filtered.items[*].id
}
