# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
# netbox_inventory_item_role can be imported by its NetBox object ID.
terraform import netbox_inventory_item_role.example 123
