# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_console_server_port_templates" "all" {}

data "netbox_console_server_port_templates" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "console_server_port_templates_ids" {
  value = data.netbox_console_server_port_templates.filtered.items[*].id
}
