# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
# netbox_cable_bundle can be imported by its NetBox object ID.
terraform import netbox_cable_bundle.example 123
