# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_prefix" "example" {
  prefix      = "10.123.0.0/24"
  description = "example"
}
