# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_owner" "example" {
  name = "example"
  group_id = netbox_owner_group.example.id
}
