# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_cables" "all" {}

data "netbox_cables" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "cables_ids" {
  value = data.netbox_cables.filtered.items[*].id
}
