# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_circuit_termination" "example" {
  circuit_id = netbox_circuit.example.id
  term_side = "A"
}
