# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_tenants" "all" {}

data "netbox_tenants" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "tenants_ids" {
  value = data.netbox_tenants.filtered.items[*].id
}
