# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_owners" "all" {}

data "netbox_owners" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "owners_ids" {
  value = data.netbox_owners.filtered.items[*].id
}
