# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
# netbox_cooling_intake can be imported by its NetBox object ID.
terraform import netbox_cooling_intake.example 123
