# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_wireless_lan" "example" {
  id = 123
}

# Lookup by arbitrary API filters:
data "netbox_wireless_lan" "filtered" {
  filters = [
    { name = "id", value = "123" },
  ]
}
