# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_tokens" "all" {}

data "netbox_tokens" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "tokens_ids" {
  value = data.netbox_tokens.filtered.items[*].id
}
