# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
# netbox_config_context can be imported by its NetBox object ID.
terraform import netbox_config_context.example 123
