# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_wireless_lans" "all" {}

data "netbox_wireless_lans" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "wireless_lans_ids" {
  value = data.netbox_wireless_lans.filtered.items[*].id
}
