# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_cluster_types" "all" {}

data "netbox_cluster_types" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "cluster_types_ids" {
  value = data.netbox_cluster_types.filtered.items[*].id
}
