# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_device_bay_template" "example" {
  device_type_id = netbox_device_type.example.id
  name = "example"
}
