# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
# netbox_vm_interface can be imported by its NetBox object ID.
terraform import netbox_vm_interface.example 123
