# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_vm_interface" "example" {
  virtual_machine_id = netbox_virtual_machine.example.id
  name = "example"
}
