# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_modules" "all" {}

data "netbox_modules" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "modules_ids" {
  value = data.netbox_modules.filtered.items[*].id
}
