# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
# netbox_power_panel can be imported by its NetBox object ID.
terraform import netbox_power_panel.example 123
