# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_power_panel" "example" {
  site_id = netbox_site.example.id
  name = "example"
}
