# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
# netbox_contact_role can be imported by its NetBox object ID.
terraform import netbox_contact_role.example 123
