# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_tag" "example" {
  name = "example-tag"
  slug = "example-tag"
}

resource "netbox_contact_role" "example" {
  name = "example"
  slug = "example"
  description = "Managed by Terraform"
  tags = [netbox_tag.example.slug]
}
