# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_devices" "all" {}

data "netbox_devices" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "devices_ids" {
  value = data.netbox_devices.filtered.items[*].id
}
