# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_power_panels" "all" {}

data "netbox_power_panels" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "power_panels_ids" {
  value = data.netbox_power_panels.filtered.items[*].id
}
