# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_cooling_source" "example" {
  site_id = netbox_site.example.id
  name = "example"
  type = "chiller"
}
