# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_module_type_profiles" "all" {}

data "netbox_module_type_profiles" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "module_type_profiles_ids" {
  value = data.netbox_module_type_profiles.filtered.items[*].id
}
