# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_ip_addresses" "all" {}

data "netbox_ip_addresses" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "ip_addresses_ids" {
  value = data.netbox_ip_addresses.filtered.items[*].id
}
