# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_cooling_outflow_template" "example" {
  name = "example"
  description = "Managed by Terraform"
}
