# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
# netbox_provider_network can be imported by its NetBox object ID.
terraform import netbox_provider_network.example 123
