# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_provider_network" "example" {
  provider_id = netbox_provider.example.id
  name = "example"
}
