# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_rack_reservations" "all" {}

data "netbox_rack_reservations" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "rack_reservations_ids" {
  value = data.netbox_rack_reservations.filtered.items[*].id
}
