# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_cable_bundles" "all" {}

data "netbox_cable_bundles" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "cable_bundles_ids" {
  value = data.netbox_cable_bundles.filtered.items[*].id
}
