# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
# netbox_circuit_type can be imported by its NetBox object ID.
terraform import netbox_circuit_type.example 123
