# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_racks" "all" {}

data "netbox_racks" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "racks_ids" {
  value = data.netbox_racks.filtered.items[*].id
}
