# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_virtual_circuit_types" "all" {}

data "netbox_virtual_circuit_types" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "virtual_circuit_types_ids" {
  value = data.netbox_virtual_circuit_types.filtered.items[*].id
}
