# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_virtual_device_contexts" "all" {}

data "netbox_virtual_device_contexts" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "virtual_device_contexts_ids" {
  value = data.netbox_virtual_device_contexts.filtered.items[*].id
}
