# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_l2vpn_termination" "example" {
  l2vpn_id = netbox_l2vpn.example.id
  assigned_object_type = "example"
  assigned_object_id = 1
}
