# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_prefixes" "all" {}

data "netbox_prefixes" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "prefixes_ids" {
  value = data.netbox_prefixes.filtered.items[*].id
}
