# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_ipam_roles" "all" {}

data "netbox_ipam_roles" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "ipam_roles_ids" {
  value = data.netbox_ipam_roles.filtered.items[*].id
}
