# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_provider_networks" "all" {}

data "netbox_provider_networks" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "provider_networks_ids" {
  value = data.netbox_provider_networks.filtered.items[*].id
}
