# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
resource "netbox_ipsec_profile" "example" {
  name = "example"
  mode = "esp"
  ike_policy_id = netbox_ike_policy.example.id
  ipsec_policy_id = netbox_ipsec_policy.example.id
}
