# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_aggregates" "all" {}

data "netbox_aggregates" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "aggregates_ids" {
  value = data.netbox_aggregates.filtered.items[*].id
}
