# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
data "netbox_data_sources" "all" {}

data "netbox_data_sources" "filtered" {
  filters = [
    { name = "q", value = "example" },
  ]
  limit = 10
}

output "data_sources_ids" {
  value = data.netbox_data_sources.filtered.items[*].id
}
