# Generated by internal/gen; edit generator/overrides to change, or remove this line to hand-maintain.
# netbox_rear_port can be imported by its NetBox object ID.
terraform import netbox_rear_port.example 123
